Revert coil to 1.3.2
Otherwise getting 
```
   > There was a failure while executing work items
      > A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingWorkAction
         > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
           Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
           Type com.google.accompanist.drawablepainter.DrawablePainter$WhenMappings is defined multiple times: /...src/accompanist/drawablepainter/build/.transforms/f1bb61ae0ebb2e13c15fa1eacd29ea35/transformed/classes/classes.dex, /.../src/accompanist/sample/build/intermediates/external_libs_dex/release/mergeExtDexRelease/classes2.dex

```